# Generated by Django 5.0.8 on 2026-05-08 12:23

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Заголовок баннера')),
                ('subtitle', models.CharField(blank=True, max_length=260, verbose_name='Подзаголовок')),
                ('badge', models.CharField(blank=True, max_length=120, verbose_name='Маленькая надпись сверху')),
                ('image', models.ImageField(blank=True, null=True, upload_to=catalog.models.upload_to_home, verbose_name='Фото баннера')),
                ('button_text', models.CharField(default='Смотреть каталог', max_length=80, verbose_name='Текст основной кнопки')),
                ('button_url', models.CharField(default='/catalog/', max_length=220, verbose_name='Ссылка основной кнопки')),
                ('second_button_text', models.CharField(blank=True, max_length=80, verbose_name='Текст второй кнопки')),
                ('second_button_url', models.CharField(blank=True, max_length=220, verbose_name='Ссылка второй кнопки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Баннер главной',
                'verbose_name_plural': 'Баннеры главной',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40, verbose_name='Число / значение')),
                ('label', models.CharField(max_length=120, verbose_name='Подпись')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Цифра на главной',
                'verbose_name_plural': 'Цифры на главной',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PromoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Заголовок акции')),
                ('subtitle', models.CharField(blank=True, max_length=180, verbose_name='Подпись')),
                ('accent_text', models.CharField(blank=True, help_text='Например: 50%, NEW, SALE', max_length=40, verbose_name='Крупный акцент')),
                ('image', models.ImageField(blank=True, null=True, upload_to=catalog.models.upload_to_home, verbose_name='Фото / фон акции')),
                ('link_text', models.CharField(default='Смотреть', max_length=80, verbose_name='Текст кнопки')),
                ('link_url', models.CharField(default='/catalog/', max_length=220, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Промо-блок главной',
                'verbose_name_plural': 'Промо-блоки главной',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['home_sort_order', '-is_featured', '-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='category',
            name='show_on_home',
            field=models.BooleanField(default=True, verbose_name='Показывать на главной'),
        ),
        migrations.AddField(
            model_name='product',
            name='badge_text',
            field=models.CharField(blank=True, help_text='Например: НОВИНКА, ХИТ, 50%', max_length=80, verbose_name='Бейдж на карточке'),
        ),
        migrations.AddField(
            model_name='product',
            name='home_sort_order',
            field=models.PositiveIntegerField(default=100, verbose_name='Порядок на главной'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_best_price',
            field=models.BooleanField(default=False, verbose_name='Хорошая цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='Хит продаж'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.CreateModel(
            name='HomeProductSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Название секции')),
                ('subtitle', models.CharField(blank=True, max_length=220, verbose_name='Подзаголовок')),
                ('badge', models.CharField(blank=True, max_length=80, verbose_name='Маленькая надпись')),
                ('source', models.CharField(choices=[('featured', 'Товары с галочкой “Показывать на главной”'), ('new', 'Новинки'), ('best_price', 'Хорошая цена'), ('bestseller', 'Хиты продаж'), ('category', 'Из выбранной категории'), ('manual', 'Выбранные вручную ниже')], default='featured', max_length=30, verbose_name='Какие товары показывать')),
                ('limit', models.PositiveIntegerField(default=8, verbose_name='Сколько товаров показать')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать секцию')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='Категория для секции')),
                ('products', models.ManyToManyField(blank=True, related_name='home_sections', to='catalog.product', verbose_name='Товары вручную')),
            ],
            options={
                'verbose_name': 'Секция товаров на главной',
                'verbose_name_plural': 'Секции товаров на главной',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
